### PR TITLE
updated bundler and readme to support for ruby 2.2 support

### PR DESCRIPTION
**Pull request by thilo**
not sure if that this is all but it looks like you get the supported ruby versions from bundler.

### CODE REVIEW

**Comment by thilo** [comment]
ok, after looking closer it seems to need a yml file somewhere too.

**Comment by fern4lvarez** [comment]
Hey, thanks for the pull request! As you have correctly guessed, it's not enough with these changes. We need to upload from our side those ruby versions to be available for the buildpack, plus the yml file that contains the list of versions.

We'll try to make these resources available, so we can merge your pull request accordignly.

**Comment by fern4lvarez** [comment]
Hey, as you might know 2.1.5 and 2.2 rubies are already available on our platform. We're not upgrading bundler for now, can you revert it to the initial 1.6.3 version so I can merge the commit? We'll keep you updated regarding this upgrade. Thanks!

**Comment by thilo** [comment]
Sure. Done.

**Pull request merged**
